arch: amd64
language: csharp
solution: DockerPrikol.sln
dotnet: 8.0.10

services:
  - docker
script: 
    -docker build -t server-dotnet Server/Docker/Ubuntu
        -docker run -p 8080:80 server-dotnet~~


        